origin: qoomon/sandbox # e.g. qoomon/sandbox

# Grant repository scoped permissions
# NOTE: Every statement will always implicitly grant `metadata: read` permission.
statements:
  - subjects:
      - repo:qoomon/sandbox:ref:refs/heads/main
    permissions: # https://docs.github.com/en/rest/authentication/permissions-required-for-github-apps
      contents: read

