name: 'CHANGE ME'
description: 'CHANGE ME'
author: 'CHANGE ME'
branding:
  icon: box
  color: blue

inputs:
  redact:
    description: 'Comma separated list of input keys to be redacted'
    required: false

runs:
  using: composite
  steps:
    - name: Log Workflow Inputs
      uses: actions/github-script@v7
      with:
        script: |
          const inputs = {
            redact: core.getInput('redact')?.split(',')?.map(it => it.trim()) ?? []
          }
  
          core.info(JSON.stringify(context.payload))

          let eventPayload
          switch (github.context.eventName) {
            case 'repository_dispatch':
              payload = context.payload.client_payload;
              break;
            case 'workflow_dispatch':
            default:
              payload = context.payload.inputs;
          }
          
          if(eventPayload) {
            core core.setOutput('payload', eventPayload);
            for (const [key, value] of Object.entries(eventPayload)) {
              core.info(`${key}: ${inputs.redact.includes(key) ? '***' : value}`)
              core.setOutput(key, value);
            }
          }
