name: 'CHANGE ME'
description: 'CHANGE ME'
author: 'CHANGE ME'
branding:
  icon: box
  color: blue

runs:
  using: composite
  steps:
    - name: Cancel Workflow
      shell: bash
      run: |
        gh run cancel ${{ github.run_id }}
        timeout 30s gh run watch ${{ github.run_id }} >/dev/null
            env:
      GH_TOKEN: ${{ github.token }}
  
