name: Build Playground

on:
  # schedule:
  #   - cron: '*/15 * * * *'
  push:
    branches:
    - master

jobs:

  playground:
    runs-on: [ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v1
    - run: env | grep GITHUB
    - run: cat $GITHUB_EVENT_PATH
    - run: |
        set -x;
        curl --request GET \
        --url https://api.github.com/repos/${{ github.repository }}/actions/runs/${{ github.run_id }} \
        --header 'authorization: Bearer ${{ github.token }}' \
        --header 'accept: application/vnd.github.antiope-preview+json'
         
