name: Update Secrets
on:
  # schedule:
  #   - cron: '*/15 * * * *'
  push:
    branches:
    - master

jobs:
  UpdateSecrets:

    runs-on: [ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v1
    - run: env | grep GITHUB
