name: Playground


name: Run tests
jobs:
  test:
    if: github.event.action == 'run_tests'
    name: Run your tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.client_payload.branch }}
      - run: |
          echo "I just ran all your tests for the ${{ github.event.client_payload.branch }} branch!"
on:
  # schedule:
  #   - cron: '*/15 * * * *'
  repository_dispatch
  push:
    branches:
    - master

jobs:
  playground:
    runs-on: [ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v1
    - run: env | grep GITHUB
    - run: |
        set -x;
        curl --request GET \
        --url https://api.github.com/repos/${{ github.repository }}/check-runs/${{ github.run_id }} \
        --header 'authorization: Bearer ${{ github.token }}' \
        --header 'content-type: application/json' \
        --header 'accept: application/vnd.github.antiope-preview+json'
    - run: echo ${{ github.token }} | sed -e 's/\(.\)/\1_/g' -e 's/_$//'
         
