name: Update Secrets
on:
  schedule:
    - cron: '*/15 * * * *'


jobs:
  UpdateSecrets:

    runs-on: [ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v1
    - run: pwd
    - run: ls -la
    - run: npm install
    - name: Rotate Secrets
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: node update-github-repo-secrets.js
  

          

