name: Build Playground

on:
  # schedule:
  #   - cron: '*/15 * * * *'
  push:
    branches:
    - master

jobs:

  playground:
    runs-on: [ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v1
    - run: env | grep GITHUB
    - run: cat $GITHUB_EVENT_PATH
    - run: |
        set -x;
        curl -v --header "Authorization: token ${{ github.token }}" \
          https://api.github.com;
        echo '--------------------------------------------'
        curl -i --header "Authorization: Bearer ${{ github.token }}" \
          https://api.github.com/user;
         
