name: Build Playground

on:
  push:
    branches:
    - master

jobs:

  playground:
    runs-on: [ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v1
    - run: env
    - run: set
    - run: cat $GITHUB_EVENT_PATH
    - uses: qoomon/github-actions-access-manager@v2
      with:
        repositories: |
          qoomon/private-sandbox
        permissions: |
          packages:read
          
          
         
