name: Build Playground

on:
  # schedule:
  #   - cron: '*/15 * * * *'
  push:
    branches:
    - master

jobs:

  playground:
    runs-on: [ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v1
    - run: set
    - run: env
    - run: cat $GITHUB_EVENT_PATH
    - run: |
        curl -i -XPOST \
          --header "Authorization: Bearer ${{ github.token }}" \
          https://api.github.com/repos/${{ github.repository }}/git/commits;
    - run: |
        curl -i -XPOST \
          --header "Authorization: Bearer ${{ github.token }}x" \
          https://api.github.com/repos/${{ github.repository }}/git/commits;
          
          
         
