name: Button Playground

on: repository_dispatch

jobs:

  playground:
    if: github.event.action == 'run_playground'
    runs-on: [ubuntu-latest]
    
    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.client_payload.ref }}
    - run: git status
    - run: echo "${{ github.event.client_payload.message }}"
