name: Create Spark
on:
  workflow_dispatch:
    inputs:
      repository:
        required: true


jobs:
  create-spark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - working-directory:
          spark
        env:
          GITHUB_TOKEN:
            ${{ secrets.TOKEN }}
        run: |
          npm install
          node create-spark.js ${{ github.event.inputs.repository }}
