name: GitHub Actions Access Manager Example

on:
  workflow_dispatch:
  push:
    branches:
    - aws-github-access-manager

permissions:
  id-token: write # This is required for requesting the JWT
  contents: read  # This is required for actions/checkout

jobs:
  sandbox:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v3
    - run: npm ci
    - run: npm start
          
          
         
