name: Manual

on: 
  workflow_dispatch:

jobs:

  run:
    runs-on: [macos-latest]
    steps:
      - uses: actions/checkout@v2
      - run: |
          cat .git/logs/HEAD
      - run: |
          cat .git/logs/HEAD
