name: Manual

on:
  push:
    branches: [ "main" ]
  
permissions:
  id-token: write # required to request id-token

jobs:

  run:
    runs-on: [ubuntu-latest]
    steps:
    - uses: qoomon/github-actions-access-manager@main
      with:
        endpoint: https://putsreq.com/aBB8O4s2D0PuDWTKlSK1 
      

