name: Manual

on: 
  workflow_dispatch:

jobs:

  run:
    runs-on: [macos-latest]
    env:
      VERSION: 0.1.5
    steps:
      - uses: actions/checkout@v2
        
      - run: curl -L "https://github.com/yulrizka/osx-push-to-talk/archive/v${VERSION}.zip" -O -J
      - run: |
          unzip "osx-push-to-talk-${VERSION}.zip"
          mv -v "osx-push-to-talk-${VERSION}"/* . 
          rm -rf "osx-push-to-talk-${VERSION}"/
          rm "osx-push-to-talk-${VERSION}.zip"
          
      - run: >
          xcodebuild -project 'PushToTalk.xcodeproj' -configuration 'Release'
          'SYMROOT=build' 'CODE_SIGN_IDENTITY=-'
            
      - uses: actions/upload-artifact@v2
        with:
          name: PushToTalk.app
          path: build/Release/PushToTalk.app
