name: Manual

on: 
  workflow_dispatch:

jobs:

  run:
    runs-on: [macos-latest]
    env:
      VERSION: 0.1.5
    steps:
      - uses: actions/checkout@v2
        with:
          repository: yulrizka/osx-push-to-talk
    
      - run: >
          xcodebuild -project 'PushToTalk.xcodeproj'
          'CODE_SIGN_IDENTITY=-'
          -configuration 'Release'
          'SYMROOT=build'
      
      - run: |
          cd build/Release/
          zip PushToTalk.app.zip PushToTalk.app 
      - uses: actions/upload-artifact@v2
        with:
          name: PushToTalk.app.zip
          path: build/Release/PushToTalk.app.zip
