name: ⚙️ Sandbox
on:
  push: 
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: sandbox-queue
  queue: max
  
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: date
      
