name: ⚙️ Sandbox
on:
  push: 
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: sandbox-queue
  queue: max
  
jobs:
  build:
    strategy:
      matrix: 
        version: [10, 12, 14]
        
    runs-on: ubuntu-latest
    steps:
      - run: sleep 1
  deploy:
    name: fuck it
    runs-on: ubuntu-latest
    steps:
      - run: sleep 1
      
