name: Trigger Workflow Deployment

on:
  push:
    branches:
    - trigger-deployment

jobs:
  build:

    runs-on: [ubuntu-latest]
    
    steps:
    - name: Trigger Deployment
      env:
        DEPLOYMENT_TARGET_ENVIRONMENT: production
        DEPLOYMENT_SOURCE_BRANCH: master
        GITHUB_REPOSITORY: ${{github.repository}}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: | 
        curl \
          -X POST \
          -H "Authorization: token ${GITHUB_TOKEN}" \
          -H "Accept: application/vnd.github.ant-man-preview+json" \
          -H "Content-Type: application/json" \
          "https://api.github.com/repos/${GITHUB_REPOSITORY}/deployments" \
          --data "{\"ref\": \"master\", \"${DEPLOYMENT_SOURCE_BRANCH}\": [], \"environment\": \"${DEPLOYMENT_TARGET_ENVIRONMENT}\"}"
