name: Trigger Workflow Hello

on:
  push:
    branches:
    - trigger-hello
    - master

jobs:
  build:

    runs-on: [ubuntu-latest]
    
    steps:
    - name: Trigger Hello Event
      env:
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_ACTOR: ${{ github.actor }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EVENT_TYPE: "hello"
        CLIENT_PAYLOAD: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
      run: |
        set -x 
        curl --fail \
          -X POST \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Content-Type: application/json" \
          "https://${GITHUB_ACTOR}:${GITHUB_TOKEN}@api.github.com/repos/${GITHUB_REPOSITORY}/dispatches" \
          --data "{\"event_type\": \"${EVENT_TYPE}\", \"client_payload\": ${CLIENT_PAYLOAD}}"

