name: Build

on:
  push:
    branches:
    - run_deployment

jobs:
  build:

    runs-on: [self-hosted]
    
    steps:
    - name: Trigger Deployment
      env:
        GITHUB_REPOSITORY: ${{github.repository}}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        EVENT_TYPE: "sandbox"
        CLIENT_PAYLOAD: '{"ref": "${{ github.ref }}", "sha": "${{ github.sha }}"}'
      run: | 
        curl \
          -X POST \
          -H "Authorization: token ${GITHUB_TOKEN}" \
          -H "Accept: application/vnd.github.ant-man-preview+json" \
          -H "Content-Type: application/json" \
          "https://api.github.com/repos/${GITHUB_REPOSITORY}/dispatches" \
          --data "{\"event_type\": \"${EVENT_TYPE}\", \"client_payload\": \"${CLIENT_PAYLOAD}\"}"

