name: Workflow Dispatch Playground

on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'  

jobs:

  playground:
    if: github.event.action == 'workflow_dispatch'
    runs-on: [ubuntu-latest]
    
    steps:
      - uses: actions/checkout@v2
      - run: echo "Log level ${{ github.event.inputs.logLevel }}"
        
